name: Vi4Interfaces
version: 1.0
authors: [XxGoldenbluexX,Hyez]
<<<<<<< Upstream, based on branch 'master' of https://github.com/XxGoldenbluexX/Vi4Interfaces.git
main: fr.xxgoldenbluexx.vi4interfaces.Vi4iMain
api-version: 1.15
commands:
  vi4i:
    description: Affiche l'interface vi4
=======
main: fr.xxgoldenbluexx.vi4interfaces.Vi4IMain
api-version: 1.15
commands:
>>>>>>> ed5322b test
